config/routes.rb
Rails.application.routes.draw do

  get '/library', to: 'library#show'

  get 'sessions/new'

  root 'main_pages#home'

  get '/help', to: 'main_pages#help'

  get '/about', to: 'main_pages#about'

  get '/contact', to: 'main_pages#contact'
  
  get '/signup', to: 'users#new'
  
  get '/signin', to: 'sessions#new'

  post '/signup', to: 'users#create'
  
  post '/signin', to: 'sessions#create'
  
  post '/add', to: 'library#create'
  
  delete '/signout', to: 'sessions#destroy'
  
  resources :users
  
  resources :songs
  
  resources :user_libraries
  
  resources :comments

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  #Library association
  has_many :user_libraries
  
  # Removing any capitalization from email before recording user
   before_save { email.downcase! }

  # Email format regular expression
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  
  # Validating length and presence of :name parameter
  validates :name, presence: true, length: {minimum: 2, maximum: 32}
  
  # Validating length, presence, format and duplication of :email parameter
  validates :email, presence: true, length: {minimum:8, maximum:64},
  							format: {with: EMAIL_REGEX},
  							uniqueness: {case_sensitive: false}
  							
  # Adding secure password
  has_secure_password
  
  # Password validations
  validates :password, presence: true, length: {minimum: 6}
  
  # Avatar validations
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/user_library.rb
class UserLibrary < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/library_controller.rb
class LibraryController < ApplicationController
  
  	def new
  		@u_lib = UserLibrary.new
  	end
  	
  	def getLibraries
  		@libraries = UserLibrary.all
  	end
  	
  	def create
  		@userID = params[:uID]
  		@songID = params[:sID]
  		@buttonID = params[:bID]
  		
  		# Check if user is logged, check if library exists, check which button is pressed and perform actions
  		if current_user == nil
  			flash[:error] = "Please sign in so you could add this song to your favourites."
  			redirect_to signin_path
  		else
  			if checkIfLibraryExists
  				checkButtonPressed(@buttonID)
  			else
  				@u_lib = UserLibrary.new
  				@u_lib.user_id = @userID
  				@u_lib.song_id = (@songID.to_i + 1).to_s
  				
  					if @u_lib.save
  						checkButtonPressed(@buttonID)
  						flash[:success] = "Song added successfully! You can now see it on your dashboard."
    					redirect_to '/library'
    				else
    					flash[:error] = "Cannot create user_library!."
  					end
  			end
  		end
  		delete
  	end
  	
  	def delete
  		getLibraries.each do |t|
  			if t.liked == false && t.liked == false && t.favorite == false
  				t.destroy
  			end
  		end
  	end
  	
  	private
  		def checkIfLibraryExists
  			UserLibrary.where(user_id: @userID, song_id: (@songID.to_i + 1).to_s).exists?
  		end
  		
  		def checkButtonPressed(btnID)
  			if btnID == 1.to_s
  				changeValueForLiked
  			else if btnID == 2.to_s
  				changeValueForDisiked
  			else if btnID == 3.to_s
  				changeValueForFavorite
  			else
  				flash[:error] = "Cannot invoke button methods!."
  			end
  			end
  			end
  		end
  		
  		def changeValueForLiked
  			if retrieveL.liked == true
  				@uLib.liked = false
  			else
  				@uLib.liked = true 
  			end
  			
  			@uLib.save
  			@uLib.reload
  		end
  		
  		def changeValueForDisliked
  			if retrieveL.disliked == true
  				@uLib.disliked = false
  			else
  				@uLib.disliked = true 
  			end
  			@uLib.save
  			@uLib.reload
  		end
  		
  		def changeValueForFavorite
  			if retrieveL.favorite == true
  				@uLib.favorite = false
  			else
  				@uLib.favorite = true
  			end
  			@uLib.save
  			@uLib.reload
  		end
  		
  		def retrieveL
  			@uLib = UserLibrary.find_by(user_id: @userID, song_id: (@songID.to_i + 1).to_s)
  		end
  	
end

app/controllers/main_pages_controller.rb
class MainPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
  
     user = User.find_by(email: params[:session][:email].downcase)
     
     if user && user.authenticate(params[:session][:password])
     
       sign_in user
       redirect_to user

     else
     
       flash.now[:danger] = 'Invalid email/password combination'
       render 'new'
    end
  end
  
  def destroy
      sign_out
    	redirect_to root_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])  
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
       flash[:success] = "Welcome to uTunes! Now Sign in using your e-mail and password!"
       redirect_to '/signin'
    else
      render 'new'
    end
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password,
      		 					:password_confirmation, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full page title on a per-page basis.

  def title(page_title = "")

	base_title = "uTunes"

	if page_title.empty?
	   base_title
	else
	   page_title + " | " + base_title
	end
  end
end

app/helpers/library_helper.rb
# library_helper.rb
# Written by Petar Zdravkov pz00073

module LibraryHelper
	
	# Method returning all songs into an array.
	def getSongs
	  @songs = Song.all
	end
	
	# Method returning all user_libraries into an array.
	def getLibraries
	  @libraries = UserLibrary.all
	end
	
	# Method returning embed url for a specific song.
   def getUrl(song)
	   "https://www.youtube.com/embed/" +  song.url + "?showinfo=0;rel=0;controls=0"
	end
	
	# Method returning thumbnail image for a specific song.
	def getThumbnail(song)
		"https://img.youtube.com/vi/" + song.url + "/0.jpg"
	end
	
	# Method updating the carousel selector when clicked on an thumbnail item.
	def updateSelectorId(index)
		"carousel-selector-" + index.to_s
	end
	
	# Method that checks if a song is liked, disliked or added in favourites and changes the
	# color of the button as marked.	
	def checkifSelected(currentIndex, buttonID)
		out = ""
		
		if buttonID == 1
			getLibraries.each do |t|
				if t.user_id == current_user.id && t.song_id == currentIndex + 1 && t.liked == true
					out = "color: #00BF9A"
				end
			end
		end
		
		if buttonID == 2
			getLibraries.each do |t|
				if t.user_id == current_user.id && t.song_id == currentIndex + 1 && t.disliked == true
					out = "color: #00BF9A"
				end
			end
		end
		
		if buttonID == 3
			getLibraries.each do |t|
				if t.user_id == current_user.id && t.song_id == currentIndex + 1 && t.favorite == true
					out = "color: gold"
				end
			end
		end
		out
	end
	
	# Method that checks if a song is liked, disliked or added in favourites and changes the
	# color of the button as marked.	
	def checkSelectedCount(currentIndex, buttonID)
		out = 0
		
		if buttonID == 1
			getLibraries.each do |t|
				if t.song_id == currentIndex + 1 && t.liked == true
					out += 1
				end
			end
		end
		
		if buttonID == 2
			getLibraries.each do |t|
				if t.song_id == currentIndex + 1 && t.disliked == true
					out += 1
				end
			end
		end
		
		if buttonID == 3
			getLibraries.each do |t|
				if t.song_id == currentIndex + 1 && t.favorite == true
					out += 1
				end
			end
		end
		
		out
	end
	
end

app/helpers/main_pages_helper.rb
module MainPagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
# Returns true if the user is logged in, false otherwise.
  def signed_in?
    !current_user.nil?
  end
  
  # Logs out the current user.
  def sign_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t('global.f_text')%> <a href="http://www.railstutorial.org/"><%= t('global.t_text')%></a>
  </small>
  <nav>
    <ul>
      <li><%= link_to t('global.about'),   about_path %></li>
      <li><%= link_to t('global.contact'), contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!-- _header.html.erb-->
<!-- Written by Petar Zdravkov pz00073-->

<!-- Header class containg main navigation through website.-->
<header class="navbar navbar-fixed-top navbar-inverse">
	
	<div class="container-fluid">
	
		<!-- Retrieving the logo. -->
		<%= link_to t('global.logo'), root_path, id: "logo" %>

		<!-- Main naviagion bar. -->
		<nav>
	  		<ul class="nav navbar-nav navbar-right">
	    		
	    		<!-- Checks if there is a user logged and changes the
	    			  presented items accordingly.							-->
	    		<% if signed_in? %>
	    		
			 		<li><%= link_to t('global.home'), current_user %></li>
			 		<li><%= link_to t('global.help'), help_path %></li>	    		
          		<li><%= link_to "Library", library_path %></li>
          
          		<!-- Drop down menu for logged users. -->
         		 <li class="dropdown">
            		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
             		 Account <b class="caret"></b>
           			</a>
            
            		<ul class="dropdown-menu">
              			<li><%= link_to "Profile", current_user %></li>
              			<li><%= link_to "Settings", '#' %></li>
              			<li class="divider"></li>
              			<li>
                			<%= link_to "Sign out", signout_path, method: :delete %>
              			</li>
            		</ul>
          		</li>
          
        		<% else %>
        			<li><%= link_to t('global.home'), root_path %></li>
        			<li><%= link_to t('global.help'), help_path %></li>
          	   <li><%= link_to t('global.log'), signin_path, class: "glyphicon glyphicon-log-in" %></li>
        		<% end %>
	  		</ul>	
		</nav>
		
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!-- application.html.erb -->
<!-- Written by Petar Zdravkov pz00073 -->
<!DOCTYPE html>
<html>
	<head>
		<!-- Function that retrieves the page title. -->
		<title><%= title(yield(:title))%></title>
		
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag    'application', media: 'all',
			'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		
		<!-- Renders the shim code. -->
		<%= render 'layouts/shim'%>
	</head>
	
	<body>
	
		<!-- Renders the navigation bar. -->
		<%= render 'layouts/header'%>
		
		<!-- Container that holds the body of the page. -->
		<div class="container">
		
			<!-- Enables the flash messages to appear. -->
			<% flash.each do |message_type, message| %>
				<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
			<% end %>
			
			<!-- Renders the content of the page. -->
			<%= yield %>
		</div>
		
	</body>
</html>

app/views/library/_actionB.html.erb
<!-- _actionB.html.erb -->
<!-- Written by Petar Zdravkov pz00073 -->

<!-- Row that holds the action buttons for each carousel item. -->
<div class="row">

	<!-- Like glyphicon button. -->
	<%= link_to add_path(local: {uID: current_user.id, sID: @i, bID: 1}), method: :post do %>
	<button type="button" class="btn btn-link actionB" style="<%= checkifSelected(@i, 1)%>" >
		<span class="glyphicon glyphicon-thumbs-up"> <%= checkSelectedCount(@i, 1)%></span>
	</button>
	<% end %>
	
	<!-- Dislike glyphicon button. -->
	<%= link_to add_path(local: {uID: current_user.id, sID: @i, bID: 2}), method: :post do %>
	<button type="button" class="btn btn-link actionB" style="<%= checkifSelected(@i, 2)%>" >
		<span class="glyphicon glyphicon-thumbs-down"> <%= checkSelectedCount(@i, 2) %></span>
	</button>
	<% end %>
	
	<!-- Add to favourites glyphicon button. -->
	<%= link_to add_path(local: {uID: current_user.id, sID: @i, bID: 3}), method: :post do %>
	<button type="button" class="btn btn-link actionB" style=" <%= checkifSelected(@i, 3)%>" >
  		<span class="glyphicon glyphicon-star"> <%= checkSelectedCount(@i, 3) %></span>
	</button>
	<% end %>
	
	<!-- Add comment modal button. -->
	<button class="btn btn-link actionB" data-toggle="modal" data-target="#myModal", data-user="<%= current_user.id %>", data-song="<%= @i %>", data-button = "4">
     <span class="glyphicon glyphicon-comment"></span>
   </button>

</div>

app/views/library/_carousel.html.erb
<!-- _carousel.html.erb --> 
<!-- Written by Petar Zdravkov pz00073 -->
 
<!-- Column that holds the slider carousel. --> 
<div class="col-sm-6 typ" id="slider">

   <div class="row">
   	<div class="col-sm-12" id="carousel-bounding-box">
      	<div class="carousel slide" id="myCarousel">
      	
         	<!-- Carousel items -->
            <div class="carousel-inner">
            
            	<div class="active item" data-slide-number="0">
            	
            		<!-- Creates the first active item and assign the parameters. -->
               	<div class="embed-responsive embed-responsive-16by9">
  							<iframe class="embed-responsive-item" src=<%= getUrl(getSongs[0])%>></iframe>
   					</div>
   					
   					<% @i = 0 %>
   						<h4><%= getSongs[@i].title %></h4>
   						<h5><%= getSongs[@i].artist %></h5>
   						<%= render 'actionB'%>
   						<%= render 'comments' %>
               </div>
                   
                  <!-- Increments the counter so all songs cold be added as items. -->
               	<% @i = 1 %>
                  <% @i.upto(getSongs.length - 1) do |t| %>
                  	<div class="item" data-slide-number=<%= @i.to_s %>>
                  	
                     	<div class="embed-responsive embed-responsive-16by9">
   								<iframe class="embed-responsive-item" src=<%= getUrl(getSongs[@i]) %> ></iframe>
  				 				</div>
  				 				
  				 				<h4><%= getSongs[@i].title %></h4>
  				 				<h5><%= getSongs[@i].artist%></h5>
  				 				<%= render 'actionB' %>
  				 				<%= render 'comments' %>
  				 			</div>
  				 			
                     <% @i += 1%>
                   <% end %>     
         	</div>
            	
            <!-- Carousel navigations. -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            	<span class="glyphicon glyphicon-chevron-left"></span></a>
                     	
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            	<span class="glyphicon glyphicon-chevron-right"></span></a>
            	
			</div>
		</div>
	</div>
</div>

app/views/library/_comment_body.html.erb
<div class="row">
	<div class="col-xs-6">
		<p>user photo</p>
	</div>
	<div class="col-xs-18">
	<div class="row">
		<p>user name</p>
	</div>
	<div class="row">
		<p>content of comment</p>
		</div>
	</div>
</div>

app/views/library/_comment_form.html.erb
<!-- _comment_form.html.erb -->
<!-- Written by Petar Zdravkov pz00073 -->

<!-- Modal that holds the comment form. -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
   	<div class="modal-content">
      	
      	<!-- Modal header. -->
      	<div class="modal-header">
        		<h4 class="modal-title" id="myModalLabel">New Comment</h4>
      	</div>
      
      	<!-- Modal body. -->
      	<div class="modal-body">
      		<div class="row">
      		
      			<!-- Image that to the logged user`s avatar. -->
      			<div class="col-md-3">
      				<%= image_tag current_user.avatar.url(:thumb), class: 'img-circle' %>
      			</div>
      			
      			<p id="para"></p>
      			
      			<!-- Form that takes the comment. -->
      			<div class="col-md-8">
      				<form>
        	 				<div class="form-group">
            				<label for="message-text" class="col-form-label">Comment:</label>
            				<textarea class="form-control" id="comment"></textarea>
         				</div>
        			 	</form>
        			</div>
        			
    			</div>	
      	</div>
     
      	<div class="modal-footer">
        		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        			<button type="button" id="submit" class="btn btn-primary">Save changes</button>
      	</div>
    </div>
  </div>
</div>

app/views/library/_comments.html.erb
<!--hahah-->
<div class="container-fluid">
	<div class="pre-scrollable container-fluid" id="comment-section">
		<%= render 'comment_body' %>
	</div>
</div>

app/views/library/_gallery.html.erb
<!-- _gallery.html.erb -->
<!-- Written by Petar Zdravkov pz00073 -->

<!-- Div that holds the responsive image gallery. -->
<div class="col-sm-6 typ" id="slider-thumbs">
   <ul class="hide-bullets list-unstyled">
   	<% i = 0 %>
		<% getSongs.each do |t| %>
			<li class="col-sm-3">
   			<a class="thumbnail" id=<%= updateSelectorId(i) %> ><img src=<%= getThumbnail(t)%>></a>
			</li>
			<% i += 1%>
		<% end %>
	</ul>
</div>

app/views/library/show.html.erb
<!-- show.html.erb -->
<!-- Written by Petar Zdravkov pz00073 -->

<!-- Function that provides the page title. -->
<%= provide(:title, "Library")%>

<!-- Pre-renders the comment modal. -->
<%= render :partial => 'library/comment_form', :remote => true %>

<!-- Container holding the main body. -->
<div class="container-fluid" id="main_c">

	<!-- Container holding the title and a short paragraph. -->
	<div class="container" id="main_c_t">
		<h4>Welcome to uTunes` library.</h4>
		<p>You can select a song, preview it and add it to your own personal favourites!</p>
	</div>
	
	<!-- Container hodling the carousel and the image grid.-->
	<div class="container-fluid">
   	<div id="main_area">
        		<div class="row" id="cars">
        			<!-- Renders the image gallery. -->
            	<%= render'gallery' %>
            	
            	<!-- Renders the slider. -->
               <%= render 'carousel' %>
        		</div>
    	</div>
	</div>
</div>

app/views/main_pages/about.html.erb
<!-- about_html.erb-->
<!-- Written by Petar Zdravkov pz00073-->

<!-- Function providing page title.-->
<% provide(:title, "About")%>

<!-- Primary div.-->
<div class="container-fluid">

  <h3><%=t('about_page.ab_m')%></h3>
    
  <div class="row">
    <div class="col-xs-6">
      <%= image_tag("photo_me.jpg", class:"img-circle", :size => "260x260", :alt => "Me") %>
    </div>

    <div class="col-xs-6">
      <h5><%= t('about_page.greet')%></h5>
      <p><%= t('about_page.text_p1') %> <%= link_to t('about_page.text_p2'), "https://www.surrey.ac.uk" %> <%= t('about_page.text_p3')%></p>
    </div>
  </div>

<hr>

<h3><%= t('about_page.ab_s')%></h3>

<br>

  <div class="row">
    <div class="col-xs-6">
      <p><%= t('about_page.text_p4')%></p>
    </div>

    <div class="col-xs-6">
      <%= image_tag("logo.png", class:"img-circle", :size => "260x260", :alt => "Me") %>
    </div>
  </div>
</div>
 <%= render 'layouts/footer'%>

app/views/main_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>MainPages#contact</h1>
<p>Find me in app/views/main_pages/contact.html.erb</p>
 <%= render 'layouts/footer'%>

app/views/main_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>MainPages#help</h1>
<p>Find me in app/views/main_pages/help.html.erb</p>
 <%= render 'layouts/footer'%>

app/views/main_pages/home.html.erb
<!-- Home.html.erb-->
<!-- Written by Petar Zdravkov pz00073-->

<!--Function providing the page title.-->
<% provide(:title, "Home")%>

<!-- Div that contains the sign up button and titles.-->
<div class="center jumbotron">

  <h2><%= t('home_page.s_title')%></h2>
  
  <div id="tdiv"> 
    <h3 id="dt"></h3>
  </div>

<!-- Div containing the carousel.-->
<div class="container-fluid">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">

      <div class="item active">
        <%=link_to image_tag("carousel_2.png", :alt => "Me"), about_path %>
      </div>

      <div class="item">
        <%=link_to image_tag("carousel_2.png", :alt => "Me"), about_path %>
      </div>
    
      <div class="item">
        <%=link_to image_tag("carousel_3.png", 	:alt => "Me"), about_path %>
      </div>
  
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<br><br>	
  <!-- Button link for sighing up.-->
  <%= link_to t('home_page.sign_btn'), signup_path , class: "btn btn-lg btn-primary" %>
   <%= render 'layouts/footer'%>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign up, now! It`s FREE!</h1>

<div class="row">
  
  <div class="co-md col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      
      <%= render 'shared/error_messages' %>      
      
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>    
    
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control'%>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<!-- show.html.erb-->
<!-- Written by Petar Zdravkov pz00073 -->

<% provide(:title, @user.name) %>


  <div class ="row">
     <div class="col-sm-6" id="acc_avatar">
       <%= image_tag @user.avatar.url(:medium), class: 'img-circle' %>
     </div>
     
     <div class="col-sm-6">
     	 <div class="row" id="acc_name">
       	<h3><%= @user.name %></h3>
       </div>
       <div class="row" id="acc_liked">
       	<h3>You currently have-----songs liked!</h3>
       </div>
       <div class="row" id="acc_lib">
       	<h3>Add more songs to your library!</h3>
       </div>
     </div>
</div>
<br>
<br>
<h4>Your Favourite Songs!</h4>
<br>
<div class="pre-scrollable container-fluid">
   <div class="row">
     
   </div>
   <div class="row">
   <div class="embed-responsive embed-responsive-16by9">
   <iframe class="embed-responsive-item" src="" ></iframe>
   </div>
   </div>
   <div class="row">
   </div>
   <br>
 </div>